### ISSUE TITLE
Storage behaviour of strings

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#257]
### Steps to reproduce
1.Create concepts in Thesaurex with String-Input
2.Add the concept as a attribute to a context in the Data Model Editor
3.Enter some Text into the added attribute in Spacialist

### Expected behaviour
The data should be saved in the backend as some kind of string

### Actual behaviour
The content is correctly displayed in the frontend. In the backend the value is stored as a complete URL in the column "thesaurus_val" of the table "attribute_values". There is no value in other columns (like "str_val"). This behaviour is the same for all attribute, which are of datatype (as visible in the datatype column of the table attribute_values) "string-mc" or "string-sc", so all the dropdown-menus.
It would be very useful, if the actual values are saved as string arrays or json-values like it is done for the datatype "epoch".

### Server configuration

**Operating system:** Ubuntu LTE 16.04

**Web server:** Apache 2.4.18

**Database:**PostgreSQL 9.5.7

**PHP version:** 7.0.18

**Lumen Version:**5.3.3

**Spacialist version:**

### Client configuration
**Browser:** Firefox 54.0

**Operating system:** Ubuntu 16.04

**Comment by derntl** [comment]
Hi David,

the behavior you are describing is by design. The single/multiple choice selections are stored as thesaurus concept URIs only.  The respective label for the concept needs to be retrieved via a query.  Storing the string value additionally would raise questions like: store the label in which language? what kind of label (pref label vs. alt label)? what happens when the thesaurus dude changes the label after the attribute value has been assigned? and so forth... all these bears a huge potential for inconsistencies. This is why we chose during DB design to store only one single value in `attribute_values` for each attribute value assignment.  The actual value to display is up to the application. In our case the displayed label is retrieved from the thesaurus whent he attribute value is displayed in Spacialist. 

An epoch is encoded as JSON since it is a complex data type, and JSON is easy to process in most environments.

I hope this clarifies the issue?
