### ISSUE TITLE
Date type: allow incomplete date or give an error

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#293]
### Steps to reproduce
1. Enter a incomplete date value (e.g. "2017") into a attribute field of type date
2. Save the editing
3. reload the page

### Expected behavior
The date should be saved as year only or there should be an error-message that says, that the date value is incorrect.
Would be nice to be able to store in one field complete dates like "01.01.2017" and incomplete ones like "2017" or "01.2017". 

### Actual behavior
The entered values just get lost without error message.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** PostgreSQL 9.5.9

**PHP version:** PHP 7.0.22

**Lumen Version:** 5.3.3

**Spacialist version:** latest master

### Client configuration
**Browser:** Firefox 56.0 (64-Bit)

**Operating system:** Ubuntu 16.04
</details>

**Comment by v1r0x** [comment]
Thanks for your report.

You shouldn't be able to enter an invalid date. The _Save_ button is disabled if one of the inputs is invalid. But it seems like I missed the round save button in the upper right corner and the _Save unstaged changes_ popup.

Unfortunately the date field has no visual feedback (should be underlined red instead of greenish) and I couldn't come up with a proper solution.
As a (temporary) solution I fix the enabled/disabled state of the other buttons.

**Comment by dirkseidensticker** [comment]
We discussed the issue and the way the date-attribute is implemented right now (as time stamp) leaves no room for incomplete dates as this would over-complicating future queries on this attribute. If you have to handle incoherent dates you might consider alternative attributes like the recently (v0.4) introduced table-attributes.
