### ISSUE TITLE
Rendering of Map-Window

### ISSUE THREAD

**Issue by DavidKi** [eScienceCenter/Spacialist#305]
### Steps to reproduce
1. Open Spacialist

### Expected behaviour
User can see complete map incl. the Map-Menu on the top

### Actual behaviour
User can see only the menu and the main part of the map. But the lower part is outside of the screen.
Would be more User-friendly if one could see the menu and the complete map (incl. the buttons on the lower part of the map).
See this screenshot:
![screen](https://user-images.githubusercontent.com/11569315/33931399-268b27d6-dff0-11e7-9c6d-7a6241e734b6.jpg)

**Comment by v1r0x** [comment]
Thanks for your report. This is a known problem, introduced in 0.3. Due to the switch to state-based routing, the listener to resize the elements to the window's height is no longer called on init. If you resize your window when loading is finished, it should resize the map, tree, etc.
Looking for a solution to fix this in one of the upcoming releases.

**Comment by DavidKi** [comment]
Thanks for looking into this! Resizing the window after loading is indeed kind of a workaround.

**Comment by v1r0x** [comment]
Fixed in #314
